### ISSUE TITLE
Ability to import previously exported search engines

### ISSUE THREAD

**Issue by fverdoja** [soufianesakhi/firefox-search-engines-helper#2]
Thank you for the amazing extension!
The extension has the ability of exporting all search engines from Firefox in a json file. It doesn't seem to me that there is the ability to use this file to import the search engines back into another Firefox profile or on another machine. Am I missing something? How should I use the json file?
If the ability to import is not yet available in any way, I think it would be a great addition to the project.

Thank you!

**Comment by soufianesakhi** [comment]
Hello,
Yes it would possible but inconvenient because there would be a prompt to add a search engine for each imported search engine.
I guess I can implement this solution, but there are no other possibility (it will be very painful to import let's say 50 search engines and having to click add 50 times !)

**Comment by soufianesakhi** [comment]
Can you test the v1.1.0 ?
There are currently limitations of 5 search engine that can be imported each 60 seconds.

**Comment by fverdoja** [comment]
Hi, sorry I had time to test it only now. It worked properly, with the limitations you pointed out, but probably those are out of your control... thank you for having implemented a solution in such a short time!
